version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: taxi_data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - taxi_network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@botlobi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8050:80"
    depends_on:
      - postgres
    networks:
      - taxi_network

  ingest:
    build: .
    image: ingest:latest
    container_name: ingest
    networks:
      - taxi_network

    command: >
      --user ${PG_USER}
      --password ${PG_PASSWORD}
      --host ${PG_HOST}
      --port ${PG_PORT}
      --db ${PG_DB}
      --table ${PG_TABLE}
      --url ${DATA_URL}
      --file ${DATA_FILE}
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  taxi_network:
    driver: bridge
